const mongoose = require('mongoose');
const Schema = mongoose.Schema;

// 1. USER SCHEMA
const UserSchema = new Schema({
  username: { type: String, required: true, unique: true },
  email: { type: String, required: true, unique: true },
  password: { type: String, required: true },
  role: { type: String, enum: ['student', 'admin'], default: 'student' },
  
  // Gamification & SP Reputation System
  spPoints: { type: Number, default: 0 },
  level: { type: Number, default: 1 },
  trustScore: { type: Number, default: 100 }, 
  contributionRating: { type: String, default: 'Novice' }, 
  helpfulAnswersCount: { type: Number, default: 0 },
  verifiedAnswersCount: { type: Number, default: 0 },
  faqContributionsCount: { type: Number, default: 0 },
  penaltiesCount: { type: Number, default: 0 },
  badges: [{ type: String }],
  
  createdAt: { type: Date, default: Date.now }
});

// 2. FAQ THREAD SCHEMA
const FAQThreadSchema = new Schema({
  title: { type: String, required: true },
  body: { type: String, required: true },
  category: { 
    type: String, 
    enum: [
      'Internship', 'Selection Process', 'Certificates', 'Attendance', 
      'Assignments', 'Mentorship', 'Projects', 'Deadlines', 
      'Technical Issues', 'Payments', 'General Queries', 'Announcements', 'Others'
    ],
    default: 'General Queries' 
  },
  author: { type: Schema.Types.ObjectId, ref: 'User', required: true },
  authorName: { type: String, required: true },
  
  upvotes: [{ type: Schema.Types.ObjectId, ref: 'User' }],
  meToo: [{ type: Schema.Types.ObjectId, ref: 'User' }],
  
  isOfficial: { type: Boolean, default: false },
  faqNumber: { type: String, default: null },  // e.g. "1.3" — null for community threads
  faqSortKey: { type: Number, default: null },  // numeric sort key, e.g. 1.03 (null for community threads) 
  isAutoGenerated: { type: Boolean, default: false }, 
  isMerged: { type: Boolean, default: false },
  mergedInto: { type: Schema.Types.ObjectId, ref: 'FAQThread', default: null },
  
<<<<<<< HEAD
  status: { type: String, enum: ['pending_review', 'active', 'flagged', 'rejected', 'merged', 'spam'], default: 'pending_review' },
  submittedForReviewAt: { type: Date, default: Date.now },
  reviewedBy: { type: Schema.Types.ObjectId, ref: 'User', default: null },
  reviewedAt: { type: Date, default: null },
  rejectionReason: { type: String, default: null },
=======
  status: { type: String, enum: ['active', 'flagged', 'merged', 'spam'], default: 'active' },
>>>>>>> ebd79f7b49a7a8f4c0860e4c38e20347dce9e852

  // Auto-Analysis Metadata
  priority: { type: String, enum: ['low', 'medium', 'high', 'urgent'], default: 'medium' },
  tags: [{ type: String }],
  summary: { type: String, default: null },
  structuredBody: {
    instruction: { type: String, default: null },
    steps: [{ type: String }],
    note: { type: String, default: null }
  },
  analysisMetadata: {
    analyzedAt: { type: Date, default: null },
    confidence: { type: Number, default: 0 },
    categoryHint: { type: String, default: null },
    priorityScore: { type: Number, default: 0 },
    keywords: [{ type: String }]
  },

  // AI Moderation Scoring Mock Metrics
  aiScores: {
    spamProbability: { type: Number, default: 0 },
    toxicityScore: { type: Number, default: 0 },
    relevanceScore: { type: Number, default: 1.0 },
    confidenceScore: { type: Number, default: 1.0 },
    qualityScore: { type: Number, default: 0.5 }
  },

  repliesCount: { type: Number, default: 0 },
  createdAt: { type: Date, default: Date.now },
  updatedAt: { type: Date, default: Date.now }
});

// 3. ANSWER SCHEMA
const AnswerSchema = new Schema({
  threadId: { type: Schema.Types.ObjectId, ref: 'FAQThread', required: true },
  body: { type: String, required: true },
  author: { type: Schema.Types.ObjectId, ref: 'User', required: true },
  authorName: { type: String, required: true },
  authorRole: { type: String, enum: ['student', 'admin'], default: 'student' },
  
  upvotes: [{ type: Schema.Types.ObjectId, ref: 'User' }],
  isVerified: { type: Boolean, default: false }, 
  isPinned: { type: Boolean, default: false },
  
  aiScores: {
    toxicityScore: { type: Number, default: 0 },
    spamProbability: { type: Number, default: 0 },
    qualityScore: { type: Number, default: 0.5 }
  },
  
  createdAt: { type: Date, default: Date.now }
});

// 4. COMMENT SCHEMA
const CommentSchema = new Schema({
  answerId: { type: Schema.Types.ObjectId, ref: 'Answer', required: true },
  body: { type: String, required: true },
  author: { type: Schema.Types.ObjectId, ref: 'User', required: true },
  authorName: { type: String, required: true },
  createdAt: { type: Date, default: Date.now }
});

// 5. NOTIFICATION SCHEMA
const NotificationSchema = new Schema({
  userId: { type: Schema.Types.ObjectId, ref: 'User', required: true },
  title: { type: String, required: true },
  message: { type: String, required: true },
  type: { 
    type: String, 
    enum: ['answer', 'sp_change', 'verification', 'reply', 'announcement', 'merge'], 
    required: true 
  },
  isRead: { type: Boolean, default: false },
  createdAt: { type: Date, default: Date.now }
});

// 6. SP TRANSACTION SCHEMA
const SPTransactionSchema = new Schema({
  userId: { type: Schema.Types.ObjectId, ref: 'User', required: true },
  pointsChange: { type: Number, required: true }, 
  reason: { type: String, required: true },      
  timestamp: { type: Date, default: Date.now }
});

// 7. BOOKMARK SCHEMA
const BookmarkSchema = new Schema({
  userId: { type: Schema.Types.ObjectId, ref: 'User', required: true },
  threadId: { type: Schema.Types.ObjectId, ref: 'FAQThread', required: true },
  createdAt: { type: Date, default: Date.now }
});
BookmarkSchema.index({ userId: 1, threadId: 1 }, { unique: true });

// 8. MODERATION LOG SCHEMA
const ModerationLogSchema = new Schema({
  targetId: { type: Schema.Types.ObjectId, required: true },
  targetType: { type: String, enum: ['thread', 'answer'], required: true },
  contentSnippet: { type: String, required: true },
  aiScores: {
    toxicityScore: { type: Number, default: 0 },
    spamProbability: { type: Number, default: 0 }
  },
  status: { type: String, enum: ['flagged', 'approved', 'removed'], default: 'flagged' },
  reviewedBy: { type: Schema.Types.ObjectId, ref: 'User', default: null },
  reviewedAt: { type: Date, default: null }
});

// 9. SEARCH LOG SCHEMA — tracks search queries for analytics
const SearchLogSchema = new Schema({
  query: { type: String, required: true },
  userId: { type: Schema.Types.ObjectId, ref: 'User', default: null }, // null = anonymous
  resultsCount: { type: Number, default: 0 },
  clickedThreadId: { type: Schema.Types.ObjectId, ref: 'FAQThread', default: null },
  source: { type: String, enum: ['faq_feed', 'search_bar', 'chatbot', 'ai_assist'], default: 'faq_feed' },
  createdAt: { type: Date, default: Date.now }
});

// 10. USER ACTIVITY SCHEMA — tracks user sessions & actions
const UserActivitySchema = new Schema({
  userId: { type: Schema.Types.ObjectId, ref: 'User', required: true },
  action: { type: String, enum: ['login', 'search', 'view_thread', 'post_answer', 'bookmark', 'upvote', 'ask_question'], required: true },
  metadata: { type: Schema.Types.Mixed, default: {} }, // extra context (threadId, searchQuery, etc.)
  createdAt: { type: Date, default: Date.now }
});

// 11. FEEDBACK SCHEMA — user feedback on answers
const FeedbackSchema = new Schema({
  answerId: { type: Schema.Types.ObjectId, ref: 'Answer', required: true },
  threadId: { type: Schema.Types.ObjectId, ref: 'FAQThread', required: true },
  userId: { type: Schema.Types.ObjectId, ref: 'User', required: true },
  rating: { type: Number, enum: [1, 2, 3, 4, 5], required: true },
  comment: { type: String, default: '' },
  sentiment: { type: String, enum: ['positive', 'neutral', 'negative'], default: 'neutral' },
  createdAt: { type: Date, default: Date.now }
});

// 12. SYSTEM METRICS SCHEMA — uptime & performance snapshots
const SystemMetricsSchema = new Schema({
  timestamp: { type: Date, default: Date.now },
  activeUsers: { type: Number, default: 0 },
  totalThreads: { type: Number, default: 0 },
  totalAnswers: { type: Number, default: 0 },
  avgResponseTimeMs: { type: Number, default: 0 },
  errorRate: { type: Number, default: 0 },
  uptimePercent: { type: Number, default: 100 }
});

// 13. FAQ TRACKER — live status tracking per thread
const FAQTrackerSchema = new Schema({
  threadId: { type: Schema.Types.ObjectId, ref: 'FAQThread', required: true, unique: true },
  status: {
    type: String,
    enum: ['received', 'ai_analyzing', 'expert_review', 'verified', 'completed'],
    default: 'received'
  },
  steps: [{ // ordered history of status transitions
    status: { type: String },
    label: { type: String },
    timestamp: { type: Date, default: Date.now },
    note: { type: String, default: '' }
  }],
  aiAnalysis: {
    summary: { type: String, default: '' },
    confidence: { type: Number, default: 0 },
    tags: [{ type: String }],
    priority: { type: String, default: 'medium' }
  },
  expertNote: { type: String, default: '' },
  completedAt: { type: Date, default: null },
  createdAt: { type: Date, default: Date.now },
  updatedAt: { type: Date, default: Date.now }
});

module.exports = {
  User: mongoose.model('User', UserSchema),
  FAQThread: mongoose.model('FAQThread', FAQThreadSchema),
  Answer: mongoose.model('Answer', AnswerSchema),
  Comment: mongoose.model('Comment', CommentSchema),
  Notification: mongoose.model('Notification', NotificationSchema),
  SPTransaction: mongoose.model('SPTransaction', SPTransactionSchema),
  ModerationLog: mongoose.model('ModerationLog', ModerationLogSchema),
  Bookmark: mongoose.model('Bookmark', BookmarkSchema),
  SearchLog: mongoose.model('SearchLog', SearchLogSchema),
  UserActivity: mongoose.model('UserActivity', UserActivitySchema),
  Feedback: mongoose.model('Feedback', FeedbackSchema),
  SystemMetrics: mongoose.model('SystemMetrics', SystemMetricsSchema),
  FAQTracker: mongoose.model('FAQTracker', FAQTrackerSchema)
};
